### ISSUE TITLE
Switch to jest

### ISSUE THREAD

**Issue by benox3** [benox3/react-pic#57]
Use jest instead of mocha for tests for caching and power of snapshots!

**Comment by frytyler** [comment]
I'm up for helping you here. Are you ok with enzyme for component tests?

**Comment by frytyler** [comment]
Sorry just saw enzyme is already there

**Comment by benox3** [comment]
Awesome, always appreciate a helping hand! Yup, currently using enzyme and mocha.

The goal here would be to switch to jest and leverage snapshot testing. As part of this switch it would be great if we could create component directories that include tests alongside the components.

Something like:
```
- common/
  - Image/
    - index.js
    - Image.js
    - Image.test.js
  - Pic/
    - index.js
    - Pic.js
    - Pic.test.js
```

**Comment by frytyler** [comment]
Cool sounds good.

How do you feel about putting the tests in a `__tests__` directory in the pattern you mentioned above. That way it follows jest's standard matching options. 

```
- common/
  - Image
    - __tests__
      - snapshots/ 
        - // snapshot files.
      - Image.test.js
    - index.js
    - Image.js
```

**Comment by benox3** [comment]
I was initially opposed to the nested directory structure for so few files, but it seems as though jest doesn't support a healthy alternative to this atm so let's follow jest's standard pattern.
